# Install/uninstall with chocolatey
- name: Ensure 7-Zip is installed through Chocolatey
  hosts: 192.168.0.4
  win_chocolatey:
    name: 7zip
    state: present

- name: Ensure 7-Zip is not installed through Chocolatey
  win_chocolatey:
    name: 7zip
    state: absent
