---
- name: Install Google Chrome on Windows Servers
  hosts: "{{ inventory }}"
  gather_facts: no
  vars:
    chrome_installer_url: https://dl.google.com/chrome/install/latest/chrome_installer.exe
    chrome_installer_path: C:\Temp\chrome_installer.exe
    chrome_exe_path: 'C:\Program Files\Google\Chrome\Application\chrome.exe'

  tasks:

    - name: Ensure Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Download Google Chrome installer
      win_get_url:
        url: "{{ chrome_installer_url }}"
        dest: "{{ chrome_installer_path }}"
        force: yes

    - name: Install Google Chrome silently using win_command
      win_command: "{{ chrome_installer_path }} /silent /install"
      args:
        creates: "{{ chrome_exe_path }}"

    - name: Verify Chrome was installed
      win_stat:
        path: "{{ chrome_exe_path }}"
      register: chrome_installed

    - name: Show success message
      debug:
        msg: "Google Chrome was installed successfully."
      when: chrome_installed.stat.exists

    - name: Remove installer
      win_file:
        path: "{{ chrome_installer_path }}"
        state: absent
