---
- name: Testowe zadanie na Windows Server
  hosts: Windows
  gather_facts: no

  tasks:
    - name: Utwórz katalog C:\TestAnsible
      win_file:
        path: C:\TestAnsible
        state: directory

    - name: Utwórz plik tekstowy z wiadomością
      win_copy:
        content: "Ansible Tower działa!"
        dest: C:\TestAnsible\hello.txt
